{% set name = "catalogue" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d01077dbfca7aa53f3ef4adecccce636bce4f82e5b52237703ab2f56478e56e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - importlib_metadata >=0.20  # [py<=37]

test:
  # The tests aren't packaged with the library, so don't bother here.
  imports:
    - catalogue

about:
  home: https://github.com/explosion/catalogue
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Super lightweight function registries for your library
  description: |
    catalogue is a tiny, zero-dependencies library that makes it easy to add
    function (or object) registries to your code. Function registries are helpful
    when you have objects that need to be both easily serializable and fully
    customizable. Instead of passing a function into your object, you pass in
    an identifier name, which the object can use to lookup the function from
    the registry. This makes the object easy to serialize, because the name
    is a simple string. If you instead saved the function, you'd have to use
    Pickle for serialization, which has many drawbacks.
  doc_url: https://github.com/explosion/catalogue
  dev_url: https://github.com/explosion/catalogue

extra:
  recipe-maintainers:
    - honnibal
    - ines
    - adrianeboyd
